CREATE TABLE "ADMIN"."CHANNELS" 
   (	"CHANNEL_ID" NUMBER, 
	"CHANNEL_DESC" VARCHAR2(20 BYTE), 
	"CHANNEL_CLASS" VARCHAR2(20 BYTE), 
	"CHANNEL_CLASS_ID" NUMBER, 
	"CHANNEL_TOTAL" VARCHAR2(13 BYTE), 
	"CHANNEL_TOTAL_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" ;


  CREATE TABLE "ADMIN"."COSTS" 
   (	"PROD_ID" NUMBER, 
	"TIME_ID" DATE, 
	"PROMO_ID" NUMBER, 
	"CHANNEL_ID" NUMBER, 
	"UNIT_COST" NUMBER(10,2), 
	"UNIT_PRICE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;


  CREATE TABLE "ADMIN"."COUNTRIES" 
   (	"COUNTRY_ID" NUMBER, 
	"COUNTRY_ISO_CODE" CHAR(2 BYTE), 
	"COUNTRY_NAME" VARCHAR2(40 BYTE), 
	"COUNTRY_SUBREGION" VARCHAR2(30 BYTE), 
	"COUNTRY_SUBREGION_ID" NUMBER, 
	"COUNTRY_REGION" VARCHAR2(20 BYTE), 
	"COUNTRY_REGION_ID" NUMBER, 
	"COUNTRY_TOTAL" VARCHAR2(11 BYTE), 
	"COUNTRY_TOTAL_ID" NUMBER, 
	"COUNTRY_NAME_HIST" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" ;


  CREATE TABLE "ADMIN"."CUSTOMERS" 
   (	"CUST_ID" NUMBER, 
	"CUST_FIRST_NAME" VARCHAR2(20 BYTE), 
	"CUST_LAST_NAME" VARCHAR2(40 BYTE), 
	"CUST_GENDER" CHAR(1 BYTE), 
	"CUST_YEAR_OF_BIRTH" NUMBER(4,0), 
	"CUST_MARITAL_STATUS" VARCHAR2(20 BYTE), 
	"CUST_STREET_ADDRESS" VARCHAR2(40 BYTE), 
	"CUST_POSTAL_CODE" VARCHAR2(10 BYTE), 
	"CUST_CITY" VARCHAR2(30 BYTE), 
	"CUST_CITY_ID" NUMBER, 
	"CUST_STATE_PROVINCE" VARCHAR2(40 BYTE), 
	"CUST_STATE_PROVINCE_ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"CUST_MAIN_PHONE_NUMBER" VARCHAR2(25 BYTE), 
	"CUST_INCOME_LEVEL" VARCHAR2(30 BYTE), 
	"CUST_CREDIT_LIMIT" NUMBER, 
	"CUST_EMAIL" VARCHAR2(50 BYTE), 
	"CUST_TOTAL" VARCHAR2(14 BYTE), 
	"CUST_TOTAL_ID" NUMBER, 
	"CUST_SRC_ID" NUMBER, 
	"CUST_EFF_FROM" DATE, 
	"CUST_EFF_TO" DATE, 
	"CUST_VALID" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" ;



  CREATE TABLE "ADMIN"."DBOCPU" 
   (	"DBPROVISIONEDOCPUS" NUMBER, 
	"CURRENT_OCPU" NUMBER, 
	"DATARETENTIONDAYS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;


  CREATE TABLE "ADMIN"."PRODUCTS" 
   (	"PROD_ID" NUMBER(6,0), 
	"PROD_NAME" VARCHAR2(50 BYTE), 
	"PROD_DESC" VARCHAR2(4000 BYTE), 
	"PROD_SUBCATEGORY" VARCHAR2(50 BYTE), 
	"PROD_SUBCATEGORY_ID" NUMBER, 
	"PROD_SUBCATEGORY_DESC" VARCHAR2(2000 BYTE), 
	"PROD_CATEGORY" VARCHAR2(50 BYTE), 
	"PROD_CATEGORY_ID" NUMBER, 
	"PROD_CATEGORY_DESC" VARCHAR2(2000 BYTE), 
	"PROD_WEIGHT_CLASS" NUMBER(3,0), 
	"PROD_UNIT_OF_MEASURE" VARCHAR2(20 BYTE), 
	"PROD_PACK_SIZE" VARCHAR2(30 BYTE), 
	"SUPPLIER_ID" NUMBER(6,0), 
	"PROD_STATUS" VARCHAR2(20 BYTE), 
	"PROD_LIST_PRICE" NUMBER(8,2), 
	"PROD_MIN_PRICE" NUMBER(8,2), 
	"PROD_TOTAL" VARCHAR2(13 BYTE), 
	"PROD_TOTAL_ID" NUMBER, 
	"PROD_SRC_ID" NUMBER, 
	"PROD_EFF_FROM" DATE, 
	"PROD_EFF_TO" DATE, 
	"PROD_VALID" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;


  CREATE TABLE "ADMIN"."PROMOTIONS" 
   (	"PROMO_ID" NUMBER(6,0), 
	"PROMO_NAME" VARCHAR2(30 BYTE), 
	"PROMO_SUBCATEGORY" VARCHAR2(30 BYTE), 
	"PROMO_SUBCATEGORY_ID" NUMBER, 
	"PROMO_CATEGORY" VARCHAR2(30 BYTE), 
	"PROMO_CATEGORY_ID" NUMBER, 
	"PROMO_COST" NUMBER(10,2), 
	"PROMO_BEGIN_DATE" DATE, 
	"PROMO_END_DATE" DATE, 
	"PROMO_TOTAL" VARCHAR2(15 BYTE), 
	"PROMO_TOTAL_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" ;


  CREATE TABLE "ADMIN"."SALES" 
   (	"PROD_ID" NUMBER, 
	"CUST_ID" NUMBER, 
	"TIME_ID" DATE, 
	"CHANNEL_ID" NUMBER, 
	"PROMO_ID" NUMBER, 
	"QUANTITY_SOLD" NUMBER(10,2), 
	"AMOUNT_SOLD" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;


  CREATE TABLE "ADMIN"."SALESTEMP" 
   (	"PROD_ID" NUMBER, 
	"CUST_ID" NUMBER, 
	"TIME_ID" DATE, 
	"CHANNEL_ID" NUMBER, 
	"PROMO_ID" NUMBER, 
	"QUANTITY_SOLD" NUMBER(10,2), 
	"AMOUNT_SOLD" NUMBER(10,2), 
	"UNIT_COST" NUMBER(10,2), 
	"UNIT_PRICE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;


  CREATE TABLE "ADMIN"."SCALING_JOB_LOG" 
   (	"EVENT_DATE" DATE, 
	"EVENT_ACTION" VARCHAR2(20 BYTE), 
	"FROM_QTY" NUMBER, 
	"TO_QTY" NUMBER, 
	"LOAD_QTY" NUMBER, 
	"MESSAGE" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;


  CREATE TABLE "ADMIN"."TIMES" 
   (	"TIME_ID" DATE, 
	"DAY_NAME" VARCHAR2(9 BYTE), 
	"DAY_NUMBER_IN_WEEK" NUMBER(1,0), 
	"DAY_NUMBER_IN_MONTH" NUMBER(2,0), 
	"CALENDAR_WEEK_NUMBER" NUMBER(2,0), 
	"FISCAL_WEEK_NUMBER" NUMBER(2,0), 
	"WEEK_ENDING_DAY" DATE, 
	"WEEK_ENDING_DAY_ID" NUMBER, 
	"CALENDAR_MONTH_NUMBER" NUMBER(2,0), 
	"FISCAL_MONTH_NUMBER" NUMBER(2,0), 
	"CALENDAR_MONTH_DESC" VARCHAR2(8 BYTE), 
	"CALENDAR_MONTH_ID" NUMBER, 
	"FISCAL_MONTH_DESC" VARCHAR2(8 BYTE), 
	"FISCAL_MONTH_ID" NUMBER, 
	"DAYS_IN_CAL_MONTH" NUMBER, 
	"DAYS_IN_FIS_MONTH" NUMBER, 
	"END_OF_CAL_MONTH" DATE, 
	"END_OF_FIS_MONTH" DATE, 
	"CALENDAR_MONTH_NAME" VARCHAR2(9 BYTE), 
	"FISCAL_MONTH_NAME" VARCHAR2(9 BYTE), 
	"CALENDAR_QUARTER_DESC" CHAR(7 BYTE), 
	"CALENDAR_QUARTER_ID" NUMBER, 
	"FISCAL_QUARTER_DESC" CHAR(7 BYTE), 
	"FISCAL_QUARTER_ID" NUMBER, 
	"DAYS_IN_CAL_QUARTER" NUMBER, 
	"DAYS_IN_FIS_QUARTER" NUMBER, 
	"END_OF_CAL_QUARTER" DATE, 
	"END_OF_FIS_QUARTER" DATE, 
	"CALENDAR_QUARTER_NUMBER" NUMBER(1,0), 
	"FISCAL_QUARTER_NUMBER" NUMBER(1,0), 
	"CALENDAR_YEAR" NUMBER(4,0), 
	"CALENDAR_YEAR_ID" NUMBER, 
	"FISCAL_YEAR" NUMBER(4,0), 
	"FISCAL_YEAR_ID" NUMBER, 
	"DAYS_IN_CAL_YEAR" NUMBER, 
	"DAYS_IN_FIS_YEAR" NUMBER, 
	"END_OF_CAL_YEAR" DATE, 
	"END_OF_FIS_YEAR" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;


  CREATE TABLE "ADMIN"."SUPPLEMENTARY_DEMOGRAPHICS" 
   (	"CUST_ID" NUMBER, 
	"EDUCATION" VARCHAR2(21 BYTE), 
	"OCCUPATION" VARCHAR2(21 BYTE), 
	"HOUSEHOLD_SIZE" VARCHAR2(21 BYTE), 
	"YRS_RESIDENCE" NUMBER, 
	"AFFINITY_CARD" NUMBER(10,0), 
	"BULK_PACK_DISKETTES" NUMBER(10,0), 
	"FLAT_PANEL_MONITOR" NUMBER(10,0), 
	"HOME_THEATER_PACKAGE" NUMBER(10,0), 
	"BOOKKEEPING_APPLICATION" NUMBER(10,0), 
	"PRINTER_SUPPLIES" NUMBER(10,0), 
	"Y_BOX_GAMES" NUMBER(10,0), 
	"OS_DOC_SET_KANJI" NUMBER(10,0), 
	"COMMENTS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 1 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" ;


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."MVW_DBOCPU" ("DBPROVISIONEDOCPUS", "CURRENT_OCPU", "DATARETENTIONDAYS") AS 
  select DBPROVISIONEDOCPUS
      ,CURRENT_OCPU
      ,DATARETENTIONDAYS
from  dbocpu;